name: nelly_virtual_asistant
description: nelly_virtual_asistant project
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # locator dependencies
  injectable: ^2.3.2
  get_it: ^7.6.4

  cupertino_icons: ^1.0.6

  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  flutter_hooks: ^0.20.3
  freezed_annotation: ^2.4.1
  loading_animation_widget: ^1.2.0+4
  permission_handler: ^11.1.0
  flutter_dotenv: ^5.1.0
  typewritertext: ^2.3.1
  auto_size_text: ^3.0.0
  image_downloader:
    git:
      url: https://github.com/VikasTailorbird/image_downloader

  speech_to_text: ^6.4.1
  text_to_speech: ^0.2.3
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  injectable_generator: ^2.4.1

  freezed: ^2.4.5

  build_runner: ^2.4.7

  flutter_launcher_icons: ^0.13.1
  rename_app: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - assets/logo/


